### ISSUE TITLE
Marker names

### ISSUE THREAD

**Issue by VictorLamoine** [InstitutMaupertuis/fanuc_grinding#12]
`/dac_marker` should probably be an generic name (like the other markers).
`/my_dilated_mesh` should probably be `/dilated_mesh` etc.

**Comment by KevinBollore** [comment]
Fixed in https://github.com/InstitutMaupertuis/fanuc_grinding/commit/aa15515fbf7f50ae9b3828e957bd44b579bf9b7e

**Comment by VictorLamoine** [comment]
+ 631ccdd  simplifies the name
