### ISSUE TITLE
Do we need execute_joint_state?

### ISSUE THREAD

**Issue by VictorLamoine** [InstitutMaupertuis/fanuc_grinding#17]
@KevinBollore please explain why we need this service.

**Comment by KevinBollore** [comment]
In a ROS service, we cannot give several joint values and execute them, the service will only execute the first one and will not execute the others.
Hence we need to call a service which execute one joint state, and call it every time we need a joint state.

**Comment by VictorLamoine** [comment]
@KevinBollore the answer is no: we don't need execute joint state as a service: #102
