### ISSUE TITLE
Send vector of robot poses in post processor widget

### ISSUE THREAD

**Issue by KevinBollore** [InstitutMaupertuis/fanuc_grinding#29]
We have to get vector of robot poses which is computed in path planning service and stored in path planning widget and send it in post processor widget.
It can be solved by the same way than #19.

**Comment by VictorLamoine** [comment]
We need to send it smartly:
- We trigger the grinder before the first pose of a "green" path (= machining)
- We stop the grinder just after the last pose of a "green path (going in extrication)

This requires splitting the trajectory into chunks.

**Comment by KevinBollore** [comment]
Yes! I forgot it when I wrote this issue.

**Comment by KevinBollore** [comment]
And if we send the vector of robot poses with the vector which says if the pose in an extrication pose or not, is it enought to identify it, isn't it?
