### ISSUE TITLE
No error in Qt when importing missing CAD file

### ISSUE THREAD

**Issue by VictorLamoine** [InstitutMaupertuis/fanuc_grinding#5]
Enter a erroneous path in the "choose a CAD file to import" and click import.
Nothing happens in the GUI.

The console shows an error because the file could not be loaded, publish_meshfile terminates;

```
ERROR: In /home/dell/libraries/vtk-v7.0.0/src/IO/Geometry/vtkSTLReader.cxx, line 106
vtkSTLReader (0x7f2aa0001690): File /home/dell/catkin_ws/src/fanuc_grinding/meshes/DAC_580813_decoupe.stl not found

ERROR: In /home/dell/libraries/vtk-v7.0.0/src/Common/ExecutionModel/vtkExecutive.cxx, line 784
vtkCompositeDataPipeline (0x7f2aa0001f70): Algorithm vtkSTLReader(0x7f2aa0001690) returned failure for request: vtkInformation (0x7f2aa00043c0)
  Debug: Off
  Modified Time: 123
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA
  FORWARD_DIRECTION: 0
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1



[publish_meshfile-8] process has died [pid 23962, exit code -11, cmd /home/dell/MEGAsync/catkin_workspace/devel/lib/publish_meshfile/publish_meshfile __name:=publish_meshfile __log:=/home/dell/.ros/log/c994aeca-224b-11e6-beb8-f01faf263c5d/publish_meshfile-8.log].
log file: /home/dell/.ros/log/c994aeca-224b-11e6-beb8-f01faf263c5d/publish_meshfile-8*.log
```

- [ ] The user should be warned that the file could not be loaded.
- [ ] The node must not terminate if the file cannot be loaded.
- [x] Filter files that can be selected with the `...` button; STL, PLY, OBJ (whatever is supported)
- [x] The default path should be set with `ros::package()`.

**Comment by KevinBollore** [comment]
Filter has been implemented in commit https://github.com/InstitutMaupertuis/fanuc_grinding/commit/b8932a5ececa06d6ee9a2774a9accdd3a8351adb

**Comment by VictorLamoine** [comment]
Closing but #10 remains
