### ISSUE TITLE
Scan button is not active

### ISSUE THREAD

**Issue by VictorLamoine** [InstitutMaupertuis/fanuc_grinding#7]
The scan cannot be launched because the button is not active

**Comment by KevinBollore** [comment]
It is because you must import a CAD mesh first.
After that an import have been made, it is possible to begin a scan.

**Comment by VictorLamoine** [comment]
Then you should disable the whole QTabWidget (Scan / Import scan) + marker button

**Comment by KevinBollore** [comment]
Fixed in https://github.com/InstitutMaupertuis/fanuc_grinding/commit/b8932a5ececa06d6ee9a2774a9accdd3a8351adb
